name: Bug Report
description: Report a bug encountered while operating k0smotron
labels:
  - bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Describe the bug in as much detail as possible.
    validations:
      required: true
  
  - type: checkboxes
    attributes:
      label: Involved Areas
      description: Indicate which areas of k0smotron are involved by this bug. More info available [here](https://docs.k0smotron.io/stable/usage-overview/)
      options:
        - label: Standalone
          required: true
        - label: Cluster API integration
          required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: |
        How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true
  
  - type: input
    id: k0smotron-version
    attributes:
      label: k0smotron version
    validations:
      required: true

  - type: input
    id: k0s-version
    attributes:
      label: k0s version
      description: |
        Use: `k0s version`
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

